remoting/client: create lockfile with explicit r+w
This fixes the compilation error below, which is triggered in hardened
build environments (e.g. NixOS):

       > In file included from /nix/store/aaaaaaaa-glibc-2.40-66-dev/include/fcntl.h:341,
       >                  from /build/source/native/remoting/client_tcp.cpp:12:
       > In function ‘int open(const char*, int, ...)’,
       >     inlined from ‘void* fmi2Instantiate(fmi2String, fmi2Type, fmi2String, fmi2String, const fmi2CallbackFunctions*, fmi2Boolean, fmi2Boolean)’ at /build/source/native/remoting/client_tcp.cpp:217:28:
       > /nix/store/aaaaaaaa-glibc-2.40-66-dev/include/bits/fcntl2.h:52:31: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
       >    52 |           __open_missing_mode ();
       >       |           ~~~~~~~~~~~~~~~~~~~~^~

In short: O_CREAT without explicit mode params may generate a file
with suid/sgid. Error triggered by _FORTIFY_SOURCE. This commit
explicitly creates the file with read/write permissions for the file
owner.

Adopted from https://github.com/facebook/hhvm/issues/168